'use strict';
const $=s=>document.querySelector(s),create=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
const subjectCode={ 'calor-frio':'CF',estructuras:'IE',fuentes:'FE',fabricacion:'SIF',adye:'ADYE',dspl:'DSPL'};
let state=null,baseState=null,tab='hoy',sha='',dirty=false,repo=localStorage.getItem('uc3m-repo')||'spotigetta/Centro-UC3M',token=sessionStorage.getItem('uc3m-token')||'';
const today=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
function saveLocal(){dirty=true;state.updated=new Date().toISOString();localStorage.setItem('uc3m-state',JSON.stringify(state));localStorage.setItem('uc3m-dirty','1');render()}
function status(text){$('#status').textContent=text}
function modal(title,draw){const body=$('#modal-body');body.replaceChildren(create('h2','',title));draw(body);$('#modal').showModal()}
function input(parent,label,value='',type='text'){const wrap=create('label');wrap.append(create('span','',label));const node=create(type==='textarea'?'textarea':'input');if(type!=='textarea')node.type=type;node.value=value;wrap.append(node);parent.append(wrap);return node}
function action(parent,text,handler,cls=''){const b=create('button',cls,text);b.type='button';b.onclick=handler;parent.append(b);return b}
const course=id=>state.subjects.find(s=>s.id===id),courseOfEvent=e=>course(e.subject),events=()=>[...(state.dataset?.events||[])].sort((a,b)=>a.date.localeCompare(b.date)||(a.time||'').localeCompare(b.time||''));
function summary(){const cards=(state.cards||[]).filter(c=>!c.checked),next=events().find(e=>e.date>=today()),projects=(state.projects||[]).filter(p=>p.status!=='Finalizado');$('#summary').replaceChildren();for(const [value,label]of [[String(cards.length),'Pendientes'],[String(projects.length),'Proyectos'],[next?next.date.slice(5):'—','Próxima fecha']]){const a=create('article');a.append(create('strong','',value),create('span','',label));$('#summary').append(a)}}
function eventCard(e){const s=courseOfEvent(e),row=create('article','event');row.style.setProperty('--color',s?.color||'#071b66');const date=create('div','date',e.date.slice(8));date.append(create('small','',new Date(e.date+'T12:00:00').toLocaleDateString('es',{month:'short'})));const line=create('span','line'),info=create('div');info.append(create('strong','',e.title),create('small','',[(s?.name||''),e.kind,e.time,e.room,e.tentative?'Fecha provisional':''].filter(Boolean).join(' · ')));row.append(date,line,info);return row}
function taskCard(c){const row=create('article','task'+(c.checked?' done':'')),check=create('input');check.type='checkbox';check.checked=!!c.checked;check.setAttribute('aria-label','Completar '+c.title);check.onchange=()=>{c.checked=check.checked;saveLocal()};const info=create('div');info.append(create('strong','',c.title),create('small','',[(c.meta?.area||''),c.meta?.due||''].filter(Boolean).join(' · ')));row.append(check,info);action(row,'Editar',()=>taskEditor(c));return row}
function taskEditor(existing){modal(existing?'Editar tarjeta':'Nueva tarjeta',body=>{const title=input(body,'Actividad',existing?.title||''),subject=input(body,'Asignatura',existing?.meta?.area||state.subjects[0]?.name||''),due=input(body,'Fecha límite',existing?.meta?.due||'','date');action(body,'Guardar',()=>{if(!title.value.trim())return;const card=existing||{id:crypto.randomUUID(),checked:false,lane:'Entrada',meta:{}};card.title=title.value.trim();card.meta.area=subject.value.trim();card.meta.areas=[card.meta.area];card.meta.due=due.value;if(!existing)state.cards.push(card);$('#modal').close();saveLocal()},'primary')})}
function groupEditor(s){const old=state.groups?.[s.id]||{};modal('Grupo · '+s.name,body=>{const name=input(body,'Número o nombre',old.name||''),members=input(body,'Integrantes, uno por línea',old.members||'','textarea'),work=input(body,'Proyecto o práctica',old.work||'','textarea'),notes=input(body,'Notas',old.notes||'','textarea');action(body,'Guardar',()=>{state.groups??={};state.groups[s.id]={name:name.value.trim(),members:members.value.trim(),work:work.value.trim(),notes:notes.value.trim()};$('#modal').close();saveLocal()},'primary')})}
function todayView(root){root.append(create('h2','section-title','Próximos 14 días'));const cutoff=new Date();cutoff.setDate(cutoff.getDate()+14);const end=cutoff.toISOString().slice(0,10),next=events().filter(e=>e.date>=today()&&e.date<=end);if(!next.length)root.append(create('p','empty','No hay sesiones previstas en los próximos 14 días.'));for(const e of next.slice(0,30))root.append(eventCard(e));root.append(create('h2','section-title','Tarjetas pendientes'));for(const c of (state.cards||[]).filter(c=>!c.checked))root.append(taskCard(c));action(root,'+ Nueva tarjeta',()=>taskEditor(),'add')}
function coursesView(root){root.append(create('h2','section-title','Segundo curso · primer cuatrimestre'));const grid=create('div','course-grid');for(const s of state.subjects){const box=create('article','course');box.style.setProperty('--color',s.color||'#071b66');const head=create('div','course-head'),icon=create('div','course-icon',subjectCode[s.id]||'UC3M'),title=create('div');title.append(create('h2','',s.name),create('small','','2026–2027 · 1C'));head.append(icon,title);box.append(head);const links=create('div','course-links');for(const [label,url]of [['Aula Global',s.campusURL],['Chat',s.chatURL]])if(url){const a=create('a','',label);a.href=url;a.target='_blank';a.rel='noopener noreferrer';links.append(a)}box.append(links);const info=state.dataset?.courses?.[s.id];if(info){const detail=create('details'),sum=create('summary','','Evaluación y prácticas'),grades=create('div','grades');detail.append(sum);for(const e of info.evaluation||[]){const row=create('div');row.append(create('span','',e.name),create('b','',e.weight==null?'':e.weight+' %'));grades.append(row)}for(const p of info.practices||[])grades.append(create('div','','⚙ '+p.title+(p.date?' · '+p.date:'')));detail.append(grades);box.append(detail)}grid.append(box)}root.append(grid)}
function calendarView(root){root.append(create('h2','section-title','Calendario académico'));let current='';for(const e of events().filter(e=>e.date>=today()).slice(0,100)){const month=e.date.slice(0,7);if(month!==current){current=month;root.append(create('h3','section-title',new Date(month+'-15T12:00:00').toLocaleDateString('es',{month:'long',year:'numeric'})))}root.append(eventCard(e))}}
function groupsView(root){root.append(create('h2','section-title','Mis grupos'));for(const s of state.subjects){const g=state.groups?.[s.id]||{},row=create('article','group'),info=create('div');info.append(create('strong','',s.name),create('p','',g.name||'Grupo sin apuntar'));if(g.members)info.append(create('small','',g.members.replace(/\n/g,' · ')));if(g.work)info.append(create('small','',' · '+g.work));row.append(info);action(row,g.name?'Editar':'Apuntar',()=>groupEditor(s));root.append(row)}}
function render(){if(!state)return;summary();for(const b of document.querySelectorAll('.tabs button'))b.classList.toggle('active',b.dataset.tab===tab);const root=$('#content');root.replaceChildren();({hoy:todayView,asignaturas:coursesView,calendario:calendarView,grupos:groupsView})[tab](root);status(dirty?'Cambios locales sin guardar en GitHub':'Datos listos · '+new Date(state.updated||Date.now()).toLocaleDateString('es'))}
function credentials(){if(!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(repo))throw Error('Configura usuario/repositorio en GitHub ⚙');if(!token)throw Error('Introduce un token con permiso Contents: read/write');return {repo,token}}
async function api(url,options={}){const response=await fetch(url,{...options,headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',Authorization:'Bearer '+token,...options.headers}}),result=await response.json().catch(()=>({}));if(!response.ok)throw Error('GitHub '+response.status+': '+(result.message||'Error'));return result}
const to64=obj=>btoa(String.fromCharCode(...new TextEncoder().encode(JSON.stringify(obj,null,2)+'\n'))),from64=value=>JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(value.replace(/\s/g,'')),x=>x.charCodeAt(0))));
async function sync(){try{credentials();status('Conectando con GitHub…');const meta=await api('https://api.github.com/repos/'+repo),branch=meta.default_branch,url='https://api.github.com/repos/'+repo+'/contents/data/state.json',remote=await api(url+'?ref='+encodeURIComponent(branch));if(dirty){if(sha&&remote.sha!==sha)throw Error('Hay cambios nuevos en GitHub. Recarga antes de guardar para evitar sobrescribirlos.');if(!sha&&JSON.stringify(from64(remote.content))!==JSON.stringify(baseState))throw Error('Hay cambios nuevos en GitHub. Recarga antes de guardar para evitar sobrescribirlos.');const update=await api(url,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Actualizar Centro UC3M desde móvil',content:to64(state),sha:remote.sha,branch})});sha=update.content.sha;dirty=false;localStorage.removeItem('uc3m-dirty');status('Guardado en GitHub');render()}else{state=from64(remote.content);sha=remote.sha;localStorage.setItem('uc3m-state',JSON.stringify(state));status('Actualizado desde GitHub');render()}}catch(e){status(e.message);alert(e.message)}}
function settings(){modal('Conectar GitHub',body=>{body.append(create('p','muted','Usa el repositorio que contiene esta PWA. El token se guarda solo en esta sesión del navegador y nunca se publica en GitHub.'));const r=input(body,'Usuario/repositorio',repo),t=input(body,'Token de acceso',token,'password');t.autocomplete='off';action(body,'Guardar conexión',()=>{repo=r.value.trim();token=t.value.trim();localStorage.setItem('uc3m-repo',repo);sessionStorage.setItem('uc3m-token',token);$('#modal').close();status('Conexión configurada; pulsa Sincronizar')},'primary')})}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});$('#sync').onclick=sync;$('#settings').onclick=settings;
(async()=>{try{const response=await fetch('data/state.json',{cache:'no-store'});if(!response.ok)throw Error('Falta data/state.json');const initial=await response.json(),local=localStorage.getItem('uc3m-state');baseState=initial;dirty=localStorage.getItem('uc3m-dirty')==='1';state=dirty&&local?JSON.parse(local):initial;render();if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('sw.js').catch(()=>{})}catch(e){status(e.message)}})();
