'use strict';
const $=s=>document.querySelector(s),el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
let state,baseState,sha='',dirty=false,tab='board',filter='',query='',repo=localStorage.getItem('uc3m-repo')||'spotigetta/Centro-UC3M',token=sessionStorage.getItem('uc3m-token')||'';
const today=()=>new Date().toISOString().slice(0,10),subjects=()=>state.subjects||[],byName=n=>subjects().find(s=>s.name===n),byId=id=>subjects().find(s=>s.id===id),events=()=>[...(state.dataset?.events||[])].sort((a,b)=>a.date.localeCompare(b.date)||(a.time||'').localeCompare(b.time||''));
function button(parent,text,fn,cls=''){const b=el('button',cls,text);b.type='button';b.onclick=fn;parent.append(b);return b}function status(t){$('#status').textContent=t}
function modal(title,draw){const body=$('#modal-body');body.replaceChildren(el('h2','',title));draw(body);$('#modal').showModal()}
function input(parent,label,value='',type='text'){const wrap=el('label');wrap.append(el('span','',label));const node=el(type==='textarea'?'textarea':type==='select'?'select':'input');if(node.tagName==='INPUT')node.type=type;node.value=value;wrap.append(node);parent.append(wrap);return node}
function saveLocal(){dirty=true;state.updated=new Date().toISOString();localStorage.setItem('uc3m-state',JSON.stringify(state));localStorage.setItem('uc3m-dirty','1');render()}
const cardSubject=c=>c.meta?.area||c.meta?.areas?.[0]||'Sin asignatura';
function digest(){const root=$('#digest');root.replaceChildren();const pending=(state.cards||[]).filter(c=>!c.checked),projects=(state.projects||[]).filter(p=>p.status!=='Finalizado'),next=events().find(e=>e.date>=today());for(const [icon,label,value,target]of [['✓','Pendientes',pending.length,'calendar'],['▣','Proyectos',projects.length,'projects'],['●','Próximo',next?.date||'—','calendar']])button(root,icon+' '+label+' · '+value,()=>{tab=target;render()},'digest-card')}
function link(parent,label,url){if(!url)return;const a=el('a','link',label);a.href=url;a.target='_blank';a.rel='noopener noreferrer';parent.append(a)}
function editCard(existing,subject){modal(existing?'Editar tarjeta':'Nueva tarjeta',body=>{const title=input(body,'Actividad',existing?.title||''),area=input(body,'Asignatura','','select');for(const s of subjects()){const o=el('option','',s.name);o.value=s.name;area.append(o)}area.value=existing?cardSubject(existing):subject?.name||subjects()[0]?.name||'';const due=input(body,'Fecha límite',existing?.meta?.due||'','date');button(body,'Guardar',()=>{if(!title.value.trim())return;const c=existing||{id:crypto.randomUUID(),checked:false,lane:'Entrada',meta:{}};c.title=title.value.trim();c.meta.area=area.value;c.meta.areas=[area.value];c.meta.due=due.value;if(!existing)(state.cards??=[]).push(c);$('#modal').close();saveLocal()},'primary')})}
function editGroup(s){const old=state.groups?.[s.id]||{};modal('Grupo · '+s.name,body=>{const name=input(body,'Número o nombre',old.name||''),members=input(body,'Integrantes, uno por línea',old.members||'','textarea'),work=input(body,'Proyecto o práctica',old.work||'','textarea'),notes=input(body,'Notas',old.notes||'','textarea');button(body,'Guardar',()=>{state.groups??={};state.groups[s.id]={name:name.value.trim(),members:members.value.trim(),work:work.value.trim(),notes:notes.value.trim()};$('#modal').close();saveLocal()},'primary')})}
function task(c){const row=el('article','task'),check=el('input');check.type='checkbox';check.checked=!!c.checked;check.onchange=()=>{c.checked=check.checked;saveLocal()};const text=el('div');text.append(el('strong','',c.title),el('small','',[c.lane,c.meta?.due].filter(Boolean).join(' · ')));row.append(check,text);button(row,'Editar',()=>editCard(c));return row}
function board(root){const grid=el('div','board');for(const s of subjects().filter(s=>!filter||s.name===filter)){const col=el('section','course-column');col.style.setProperty('--color',s.color||'#000066');const head=el('header');head.append(el('span','course-icon',(s.icon||'UC').slice(0,2).toUpperCase()),el('h2','',s.name));col.append(head);const links=el('div','links');link(links,'Aula Global',s.campusURL);link(links,'Chat de la asignatura',s.chatURL);col.append(links);const group=state.groups?.[s.id]||{},groupBox=el('section','group-box');groupBox.append(el('strong','','♙ Mi grupo'+(group.name?' · '+group.name:'')));if(group.members)groupBox.append(el('small','',group.members.replace(/\n/g,' · ')));if(group.work)groupBox.append(el('small','',group.work));button(groupBox,group.name||group.members?'Editar':'Apuntar grupo',()=>editGroup(s));col.append(groupBox);const info=state.dataset?.courses?.[s.id];if(info){const details=el('details','course-details');details.append(el('summary','','Evaluación y prácticas'));for(const g of info.evaluation||[]){const r=el('div','grade');r.append(el('span','',g.name),el('b','',g.weight==null?'':g.weight+' %'));details.append(r)}for(const p of info.practices||[])details.append(el('div','practice','⚗ '+p.title+(p.date?' · '+p.date:' · fecha pendiente')));col.append(details)}const next=events().find(e=>e.subject===s.id&&e.date>=today());if(next)col.append(el('div','next','PRÓXIMO · '+next.date+'\n'+next.title));const list=el('div','tasks');for(const c of (state.cards||[]).filter(c=>cardSubject(c)===s.name))list.append(task(c));button(list,'＋ Nueva tarjeta',()=>editCard(null,s),'add');col.append(list);const files=(state.files||[]).filter(f=>f.subject===s.id);if(files.length){const docs=el('details','files');docs.append(el('summary','',`Material · ${files.length} archivos`));for(const f of files.slice(0,100))docs.append(el('div','file',f.name));col.append(docs)}grid.append(col)}root.append(grid)}
function calendar(root){root.append(el('h2','section-title','Calendario'));let month='';for(const e of events().filter(e=>e.date>=today()&&(!filter||byId(e.subject)?.name===filter)).slice(0,120)){const m=e.date.slice(0,7);if(m!==month){month=m;root.append(el('h3','month',new Date(m+'-15T12:00:00').toLocaleDateString('es-ES',{month:'long',year:'numeric'})))}const row=el('article','event');row.style.setProperty('--color',byId(e.subject)?.color||'#000066');row.append(el('time','',e.date+(e.time?' · '+e.time:'')),el('strong','',e.title),el('small','',[byId(e.subject)?.name,e.kind,e.room].filter(Boolean).join(' · ')));root.append(row)}}
function projects(root){listView(root,'Proyectos',state.projects||[],p=>[p.name,p.description,[p.status,...(p.areas||[])].filter(Boolean).join(' · ')])}function notes(root){listView(root,'Apuntes',state.notes||[],n=>[n.title,n.text,''])}function reports(root){listView(root,'Informes y presentaciones',state.reports||[],r=>[r.name,r.path||'',''])}
function listView(root,title,items,map){root.append(el('h2','section-title',title));if(!items.length)root.append(el('p','empty','No hay elementos registrados.'));for(const item of items){const [name,text,meta]=map(item),box=el('article','item');box.append(el('strong','',name));if(text)box.append(el('p','',text));if(meta)box.append(el('small','',meta));root.append(box)}}
function searchView(root){root.append(el('h2','section-title','Resultados'));const q=query.toLocaleLowerCase('es'),hits=[],add=(kind,title,detail='')=>{if((title+' '+detail).toLocaleLowerCase('es').includes(q))hits.push({kind,title,detail})};for(const s of subjects())add('Asignatura',s.name);for(const c of state.cards||[])add('Tarjeta',c.title,cardSubject(c)+' '+(c.meta?.due||''));for(const p of state.projects||[])add('Proyecto',p.name,p.description);for(const n of state.notes||[])add('Apunte',n.title,n.text);for(const e of events())add(e.kind||'Evento',e.title,e.date+' '+(byId(e.subject)?.name||''));for(const f of state.files||[])add('Archivo',f.name,f.path);for(const h of hits.slice(0,180)){const row=el('article','search-result');row.append(el('b','',h.kind+' · '+h.title),el('small','',h.detail));root.append(row)}if(!hits.length)root.append(el('p','empty','Sin resultados.'))}
function render(){if(!state)return;digest();for(const b of document.querySelectorAll('.tabs button'))b.classList.toggle('active',b.dataset.tab===tab);const root=$('#content');root.replaceChildren();if(query)searchView(root);else({board,calendar,projects,notes,reports}[tab]||board)(root);status(dirty?'Cambios locales sin guardar en GitHub':'Datos listos · '+new Date(state.updated||Date.now()).toLocaleDateString('es-ES'))}
function credentials(){if(!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(repo))throw Error('Configura usuario/repositorio');if(!token)throw Error('Introduce un token con permiso Contents: read/write')}
async function api(url,options={}){const response=await fetch(url,{...options,headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',Authorization:'Bearer '+token,...options.headers}}),result=await response.json().catch(()=>({}));if(!response.ok)throw Error('GitHub '+response.status+': '+(result.message||'Error'));return result}const to64=obj=>btoa(String.fromCharCode(...new TextEncoder().encode(JSON.stringify(obj,null,2)+'\n'))),from64=value=>JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(value.replace(/\s/g,'')),x=>x.charCodeAt(0))));
async function sync(){try{credentials();status('Conectando con GitHub…');const meta=await api('https://api.github.com/repos/'+repo),branch=meta.default_branch,url='https://api.github.com/repos/'+repo+'/contents/data/state.json',remote=await api(url+'?ref='+encodeURIComponent(branch));if(dirty){if(sha&&remote.sha!==sha)throw Error('Hay cambios nuevos en GitHub. Recarga antes de guardar.');if(!sha&&JSON.stringify(from64(remote.content))!==JSON.stringify(baseState))throw Error('Hay cambios nuevos en GitHub. Recarga antes de guardar.');const update=await api(url,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Actualizar Centro UC3M desde móvil',content:to64(state),sha:remote.sha,branch})});sha=update.content.sha;dirty=false;localStorage.removeItem('uc3m-dirty')}else{state=from64(remote.content);baseState=structuredClone(state);sha=remote.sha;localStorage.setItem('uc3m-state',JSON.stringify(state))}render()}catch(e){status(e.message);alert(e.message)}}
function settings(){modal('Conectar GitHub',body=>{body.append(el('p','muted','El token permanece solo durante esta sesión y no se publica.'));const r=input(body,'Usuario/repositorio',repo),t=input(body,'Token',token,'password');button(body,'Guardar conexión',()=>{repo=r.value.trim();token=t.value.trim();localStorage.setItem('uc3m-repo',repo);sessionStorage.setItem('uc3m-token',token);$('#modal').close();status('Conexión configurada')},'primary')})}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;query='';$('#search').value='';render()});$('#new-card').onclick=()=>editCard();$('#sync').onclick=sync;$('#settings').onclick=settings;$('#search').oninput=e=>{query=e.target.value.trim();render()};$('#subject-filter').onchange=e=>{filter=e.target.value;render()};
(async()=>{try{const response=await fetch('data/state.json',{cache:'no-store'});if(!response.ok)throw Error('Falta data/state.json');const initial=await response.json(),local=localStorage.getItem('uc3m-state');baseState=structuredClone(initial);dirty=localStorage.getItem('uc3m-dirty')==='1';state=dirty&&local?JSON.parse(local):initial;for(const s of subjects()){const o=el('option','',s.name);o.value=s.name;$('#subject-filter').append(o)}render();if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('sw.js').catch(()=>{})}catch(e){status(e.message)}})();
